### ISSUE TITLE
Multiple Environments

### ISSUE THREAD

**Issue by PokeyOne** [PokeyOne/pokey-logger#14]
Allow configuration of multiple environments. For example there would be a default environment, but there would also be the ability to have as many as saw fit. Some special ones should exist though, such as `test` should automatically be used when testing, and `production` should be used when compiled for release, and `development` should be used when just running through normal cargo.

An example config file might look like:
```yaml
default:
  some_setting: "value"
test:
  some_setting: "test value"
production:
  some_setting: "real value"
```
